name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Libssl
        run: |
          wget https://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

      - name: Install Aiken
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://install.aiken-lang.org | sh
          ~/.aiken/bin/aikup install v1.0.29-alpha
          sudo ln -s ~/.aiken/bin/aiken /usr/local/bin/aiken

      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
